# Generated by Django 4.2.11 on 2026-03-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscribers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("preview_text", models.CharField(max_length=300)),
                ("article_url", models.URLField(max_length=500)),
                ("html_content", models.TextField()),
                ("plain_text_content", models.TextField()),
                ("published_date", models.DateField(db_index=True)),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="CampaignSend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[("scheduled", "Scheduled"), ("manual", "Manual")],
                        max_length=10,
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("total_sent", models.IntegerField(default=0)),
                ("total_failed", models.IntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sends",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Send",
                "verbose_name_plural": "Campaign Sends",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_logs",
                        to="subscribers.subscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Log",
                "verbose_name_plural": "Campaign Logs",
                "ordering": ["-sent_at"],
                "unique_together": {("campaign", "subscriber")},
            },
        ),
    ]
